baseurl: "https://shitops.de"
title: "ShitOps"
languageCode: "en-us"
theme: "hello-friend-ng"
paginate: 50
disqusShortname: "shitops"

params:
  dateform: "Jan 2, 2006"
  dateformShort: "Jan 2"
  dateformNum: "2006-01-02"
  dateformNumTime: "2006-01-02 15:04"
  homeSubtitle: "Powered by Chat Jippity"
  disableReadOtherPosts: false
  enableSharingButtons: true
  enableGlobalLanguageMenu: false
  enableThemeToggle: true
  description: "Technical Solutions for the 10X Engineers"
  keywords: "blog, engineering, engineeringblog, solutions, architecture, engineering, solutions"
  images:
    - ""
  mermaid:
    theme: "dark"
    align: "center"
  footer:
    rss: true
  favicon:
    color:
      mask: "#1b1c1d"
      msapplication: "#1b1c1d"
      theme: "#1b1c1d"
  search:
    enable: true
    backend: "fuse"
  plausible:
    enable: true
    selfhosted_domain: "plausible.chaops.de"
    domain: plausible.chaops.de
    outbound_link: true
    file_downloads: true
    debug: false
    gitstar: false

taxonomies:
  category: "blog"
  tag: "tags"
  series: "series"

languages:
  en:
    title: "Technical Solutions for the 10X Engineers"
    params:
      subtitle: "Powered by ChatGPT"
      readOtherPosts: "Read other posts"
      logo:
        logoText: "Extreme engineering"
        logoHomeLink: "/"
      # or
      # path: "/img/your-example-logo.svg"
      # alt: "Your example logo alt text"

menu:
  main:
    - identifier: "blog"
      name: "Blog"
      url: "/posts"
      weight: 10
    - identifier: "career"
      name: "Career"
      url: "/career"
      weight: 20
    - identifier: "about"
      name: "About"
      url: "/about"
      weight: 30
    - identifier: "search"
      name: "Search"
      url: "/search"
      weight: 40

outputFormats:
  SearchIndex:
    baseName: search
    mediaType: application/json

outputs:
  home:
    - HTML
    - RSS
    # - SearchIndex
    - JSON

module:
  imports:
    - path: "github.com/divinerites/plausible-hugo"
