baseurl      = "https://shitops.de"
title        = "ShitOps"
languageCode = "en-us"
theme        = "hello-friend-ng"
paginate     = 10
disqusShortname = "shitops"

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"

  # Subtitle for home
  homeSubtitle = "Powered by ChatGPT"

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Enable sharing buttons, if you like
  enableSharingButtons = true

  # Show a global language switcher in the navigation bar
  enableGlobalLanguageMenu = false

  # Metadata mostly used in document's head
  description = "Technical Solutions for the 10x Engineers"
  keywords = "blog, engineering, engineeringblog, solutions, architecture, engineering, solutions"
  images = [""]

  [params.mermaid]
    theme = "dark"
    align = "center"

[taxonomies]
    category = "blog"
    tag      = "tags"
    series   = "series"

[languages]
  [languages.en]
    title = "Technical Solutions for the 10x Engineers"
    subtitle = "Powered by ChatGPT"
    # copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "Extreme engineering"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

  # And you can even create generic menu
  [[menu.main]]
    identifier = "blog"
    name       = "Blog"
    url        = "/posts"
  [[menu.main]]
    identifier = "rrs-feed"
    name       = "RSS"
    url        = "/index.xml"
